#!/bin/sh
#
function clean_up() {

	## SHRINKING FILESIZE BY REMOVING INSIDED DEBUGGING SYMBOLS

	apac=( httpd ab fcgistarter htcacheclean htdbm htdigest htpasswd logresolve rotatelogs )
	ph=( php php-cgi phpdbg )
	depen=( bison pcregrep pcretest re2c )
	single=( 'php/sbin/php-fpm' 'httpd/modules/libphp7.so' )

	## SINGLE
	for s in "${single[@]}"; do
		objcopy --strip-debug $OPENSHIFT_DATA_DIR/$s
	done

	## PHP
	for p in "${ph[@]}"; do
		objcopy --strip-debug $OPENSHIFT_DATA_DIR/php/bin/$p
	done

	## APACHE
	for a in "${apac[@]}"; do
		objcopy --strip-debug $OPENSHIFT_DATA_DIR/httpd/bin/$a
	done

	## DEPENDENCIES
	for d in "${depen[@]}";	do
		objcopy --strip-debug $OPENSHIFT_RUNTIME_DIR/dependencies/bin/$d
	done
	}

	## COPY SETTING FILES

	cp $OPENSHIFT_REPO_DIR/conf/bash_profile.tpl $OPENSHIFT_DATA_DIR/.bash_profile
	python $OPENSHIFT_REPO_DIR/setup/conf.py

}

function start_server() {
	httpd -f $OPENSHIFT_REPO_DIR/conf/shutdown.conf -k stop
	$OPENSHIFT_DATA_DIR/httpd/bin/apachectl start
}

function wipe_out() {
	cd $OPENSHIFT_REPO_DIR
	rm -rf conf setup htdocs/index.cgi
	hoo=( build reload restart start stop )
	for h in "${hoo[@]}"; do
		cd $OPENSHIFT_REPO_DIR/.openshift/action_hooks
		rm -f $h
		mv $h.tpl $h
		chmod +x $h
	done
}
