#!/bin/bash

function install_dep() {

### INSTALL PCRE
	cd $OPENSHIFT_RUNTIME_DIR
	if [ ! -e dependencies/lib/libpcre.a ]; then
		if [ ! -e pcre-"$PCRE_VERSION".tar.gz ]; then
		wget "$PCRE_MIRROR"/pcre-"$PCRE_VERSION".tar.gz
		fi
	rm -rf pcre-$PCRE_VERSION
	tar -xvzf pcre-$PCRE_VERSION.tar.gz
	cd pcre-$PCRE_VERSION
	./configure -C --prefix=$OPENSHIFT_RUNTIME_DIR/dependencies --disable-cpp --enable-unicode-properties
	./config.status -q
	make -s -j3 V=0 || make
	make -s install V=0
		if [ $? -eq 0 ]; then
			echo "PCRE has successfully been installed!"
			rm -rf $OPENSHIFT_RUNTIME_DIR/pcre-*
		else
			echo "The installation of PCRE has been interrupted."
		fi
	else
		echo "PCRE has already been installed!"
	fi

### INSTALL APR

	cd $OPENSHIFT_RUNTIME_DIR
	if [ ! -e dependencies/include/apr-1 ]; then
		if [ ! -e apr-$APR_VERSION.tar.gz ]; then
		wget $APR_MIRROR/apr-$APR_VERSION.tar.gz
		fi
	rm -rf apr-$APR_VERSION
	tar -xvzf apr-$APR_VERSION.tar.gz
	cd apr-$APR_VERSION
	./configure -C --prefix=$OPENSHIFT_RUNTIME_DIR/dependencies --enable-nonportable-atomics
	./config.status -q
	make -s -j3 V=0 || make
	make -s install V=0
		if [ $? -eq 0 ]; then
			echo "APR has successfully been installed!"
			rm -rf $OPENSHIFT_RUNTIME_DIR/apr-*
		else
			echo "The installation of APR has been interrupted."
		fi
	else
		echo "APR has already been installed!"
	fi

### INSTALL APU

	cd $OPENSHIFT_RUNTIME_DIR
	if [ ! -e dependencies/bin/apu-1-config ]; then
		if [ ! -e apr-util-$APU_VERSION.tar.gz ]; then
		wget $APR_MIRROR/apr-util-$APU_VERSION.tar.gz
		fi
	rm -rf apr-util-$APU_VERSION
	tar -xvzf apr-util-$APU_VERSION.tar.gz
	cd apr-util-$APU_VERSION
	./configure -C --prefix=$OPENSHIFT_RUNTIME_DIR/dependencies --with-apr=$OPENSHIFT_RUNTIME_DIR/dependencies
	./config.status -q
	make -s -j3 V=0 || make
	make -s install V=0
		if [ $? -eq 0 ]; then
			echo "APU has successfully been installed!"
			rm -rf $OPENSHIFT_RUNTIME_DIR/apr-*
		else
			echo "The installation of APU has been interrupted."
		fi
	else
		echo "APU has already been installed!"
	fi

}