#!/bin/bash
#
source $OPENSHIFT_REPO_DIR/setup/install_dep
source $OPENSHIFT_REPO_DIR/setup/finish_up

function install_apache() {
	
	## INSTALL APACHE

	cd ${OPENSHIFT_DATA_DIR}
if [ ! -e httpd ]; then
	if [ -e httpd-${APACHE_VERSION}.tar.gz ]; then
		echo "Found APACHE source code, skip downloading."
	else
		echo "Downloading APACHE source code"
		wget -nv ${APACHE_MIRROR}/httpd-${APACHE_VERSION}.tar.gz && \
	  if [ $? != 0 ]; then
		echo "ERROR! CANNOT DOWNLOAD httpd-${APACHE_VERSION}"
		return 1
	  fi
	fi
	
	tar -zxf httpd-${APACHE_VERSION}.tar.gz
	cd httpd-${APACHE_VERSION}
		
	[ ! -f Makefile ] && \
	./configure -C --prefix=$OPENSHIFT_DATA_DIR/httpd \
	--enable-so --enable-http --enable-rewrite --enable-proxy --enable-proxy-connect --enable-proxy-http --with-mpm=prefork \
	--with-apr=$OPENSHIFT_RUNTIME_DIR/dependencies --with-apr-util=$OPENSHIFT_RUNTIME_DIR/dependencies --with-pcre=$OPENSHIFT_RUNTIME_DIR/dependencies
	make
	make install
	if [ $? -eq 0 ]; then
		echo "APACHE has successfully been installed!"
		rm -rf $OPENSHIFT_DATA_DIR/httpd-*
	else
		echo "The installation of APACHE has been interrupted!"
	fi
else
	echo "APACHE has already been installed!"
fi
}

function install_php() {

	## INSTALL PHP

	cd ${OPENSHIFT_DATA_DIR}
if [ ! -e php ]; then
	if [ -e php-${PHP_VERSION}.tar.gz ]; then
		echo "Found PHP source code, skip downloading."
	else
		echo "Downloading PHP source code"
		wget -nv $PHP_MIRROR/php-${PHP_VERSION}.tar.gz && \
	  if [ $? != 0 ]; then
		echo "ERROR! CANNOT DOWNLOAD php-${PHP_VERSION}"
		return 1
	  fi
	fi

	tar -zxf php-$PHP_VERSION.tar.gz
	cd php-${PHP_VERSION}
		
	[ ! -f Makefile ] && \
	./configure \
	--with-libdir=lib64 \
	--prefix=$OPENSHIFT_DATA_DIR/php/ \
	--with-config-file-path=$OPENSHIFT_DATA_DIR/php/etc \
	--with-apxs2=$OPENSHIFT_DATA_DIR/httpd/bin/apxs \
	--with-zlib=$OPENSHIFT_RUNTIME_DIR/dependencies \
	--with-icu-dir=$OPENSHIFT_RUNTIME_DIR/dependencies \
	--with-layout=PHP --with-gd --enable-zip --enable-mbstring --enable-intl --enable-opcache
	make
	make install
	if [ $? -eq 0 ]; then
		echo "PHP has successfully been installed!"
		rm -rf $OPENSHIFT_DATA_DIR/php-*
	else
		echo "The installation of PHP has been interrupted!"
	fi
else
	echo "PHP has already been installed!"
fi
}

function check_php() {
	if [[ -x $OPENSHIFT_DATA_DIR/php/bin/php-cgi ]] && \
	   [[ "`$OPENSHIFT_DATA_DIR/php/bin/php-cgi`" =~ "${PHP_VERSION}" ]] 
	then
		return 0
	fi
	
	echo "Checking... PHP ${PHP_VERSION} doesn't exist! Start installing..."
	install_dep
	install_apache
	install_php
	clean_up
	start_server
	wipe_out
}
